apiVersion: hybridsovereign.redhat/v1alpha1
kind: CloudGateway
metadata:
  name: aws-us-east-1
  namespace: sovereign-cloud
spec:
  enabled: true
  cloud: aws
  region: us-east-1
  domainAsn: 65001
  fabricRef: lab-fabric
  transport:
    type: wireguard
