apiVersion: hybridsovereign.redhat/v1alpha1
kind: UIHealthChecker
metadata:
  name: quay-signal9
  namespace: sovereign-cloud
spec:
  displayName: Quay Registry
  group: quay
  url: https://quay.signal9.gg/
  expectedStatus: 200
---
apiVersion: hybridsovereign.redhat/v1alpha1
kind: UIHealthChecker
metadata:
  name: vault-central
  namespace: sovereign-cloud
spec:
  displayName: Vault Central
  group: central
  url: https://vault-central.apps.shc-cental5.lab.signal9.gg/
  expectedStatus: 200
---
apiVersion: hybridsovereign.redhat/v1alpha1
kind: UIHealthChecker
metadata:
  name: vault-services
  namespace: sovereign-cloud
spec:
  displayName: Vault Services
  group: services
  url: https://vault-services.apps.shc-services5.lab.signal9.gg/
  expectedStatus: 200
---
apiVersion: hybridsovereign.redhat/v1alpha1
kind: UIHealthChecker
metadata:
  name: rhbk-central
  namespace: sovereign-cloud
spec:
  displayName: RHBK Central
  group: central
  url: https://rhbk-central.apps.shc-cental5.lab.signal9.gg/
  expectedStatus: 200
---
apiVersion: hybridsovereign.redhat/v1alpha1
kind: UIHealthChecker
metadata:
  name: rhbk-services
  namespace: sovereign-cloud
spec:
  displayName: RHBK Services
  group: services
  url: https://rhbk-services.apps.shc-services5.lab.signal9.gg/
  expectedStatus: 200
---
apiVersion: hybridsovereign.redhat/v1alpha1
kind: UIHealthChecker
metadata:
  name: gitea-central
  namespace: sovereign-cloud
spec:
  displayName: Gitea
  group: central
  url: https://gitea-gitea.apps.shc-cental5.lab.signal9.gg/
  expectedStatus: 200
---
apiVersion: hybridsovereign.redhat/v1alpha1
kind: UIHealthChecker
metadata:
  name: aap-central
  namespace: sovereign-cloud
spec:
  displayName: AAP Gateway
  group: central
  url: https://sovereign-aap-aap.apps.shc-cental5.lab.signal9.gg/
  expectedStatus: 200
