---
quay_url: "{{ lookup('env', 'QUAY_URL') | default('https://svc-sovereign-registry-quay-quay-enterprise.apps.services.lab.example.com', true) }}"
plugin_quay_config_namespace: sovereign-cloud-plugins
