---
cloudaws_operator_namespace: sovereign-cloud
central_api_server: "https://api.central.lab.example.com:6443"
central_sa_secret_name: awshelper-creator-sa
central_sa_secret_namespace: sovereign-cloud
