---
aap_controller_url: "{{ lookup('env', 'AAP_CONTROLLER_URL') | default('https://sovereign-aap-controller-aap.apps.services.lab.example.com', true) }}"
aap_gateway_url: "{{ lookup('env', 'AAP_GATEWAY_URL') | default('https://sovereign-aap-aap.apps.services.lab.example.com', true) }}"
aap_gateway_internal_url: "{{ lookup('env', 'AAP_GATEWAY_INTERNAL_URL') | default('http://sovereign-aap.aap.svc:80', true) }}"
plugin_aap_config_namespace: sovereign-cloud-plugins
