##@ Lab config (env → Vault)

LAB_ENV_FILE ?= $(CURDIR)/../.env
ifeq ($(wildcard $(LAB_ENV_FILE)),)
  LAB_ENV_FILE := $(CURDIR)/.env
endif
ifeq ($(wildcard $(LAB_ENV_FILE)),)
  LAB_ENV_FILE := $(abspath $(CURDIR)/../.env)
endif

LAB_VAULT_PATH ?= central/data/lab-config
LAB_CONFIGMAP_NS ?= openshift-gitops
LAB_CONFIGMAP_NAME ?= lab-config

# Non-secret topology keys uploaded to Vault / ConfigMap
LAB_CONFIG_KEYS := \
  LAB_DOMAIN BASE_DOMAIN CENTRAL_CLUSTER_NAME SERVICES_CLUSTER_NAME APPS_SUBDOMAIN \
  OCI_REPOSITORY_BASE CENTRAL_APPS_DOMAIN SERVICES_APPS_DOMAIN OCI_HOST \
  DNS_FORWARDER_ZONE DNS_FORWARDER_IPS \
  OCP_CENTRAL_SERVER OCP_SERVICES_SERVER \
  VAULT_CENTRAL_URL VAULT_SERVICES_URL \
  RHBK_CENTRAL_URL RHBK_SERVICES_URL \
  GITEA_URL KAFKA_EXTERNAL_BOOTSTRAP KAFKA_BOOTSTRAP_HOST \
  AAP_CENTRAL_GATEWAY_URL AAP_CENTRAL_CONTROLLER_URL \
  AAP_SERVICES_GATEWAY_URL AAP_SERVICES_CONTROLLER_URL \
  QUAY_CENTRAL_URL QUAY_SERVICES_URL ACS_CENTRAL_URL \
  S3_ENDPOINT VMWARE_VCENTER_URL CLUSTER_BUILDS_REPO_URL

.PHONY: load-lab-env
load-lab-env: ## Source local .env into the current make process (use: set -a && . ./.env)
	@test -f "$(LAB_ENV_FILE)" || { echo "Missing $(LAB_ENV_FILE) — copy .env.example to .env"; exit 1; }
	@echo "Lab env file: $(LAB_ENV_FILE)"

.PHONY: render-values-lab
render-values-lab: ## Generate gitignored values-lab.yaml from .env
	@test -f "$(LAB_ENV_FILE)" || { echo "Missing $(LAB_ENV_FILE)"; exit 1; }
	@set -a; . "$(LAB_ENV_FILE)"; set +a; \
	outdir="$(CURDIR)/helm/central"; \
	mkdir -p "$$outdir"; \
	ips_yaml=$$(echo "$${DNS_FORWARDER_IPS}" | tr ',' '\n' | sed '/^$$/d;s/^/    - "/;s/$$/"/'); \
	{ \
	  echo '# GENERATED from .env — DO NOT COMMIT'; \
	  echo '# Regenerated by: make render-values-lab'; \
	  echo 'lab:'; \
	  echo "  domain: \"$${LAB_DOMAIN}\""; \
	  echo "  baseDomain: \"$${BASE_DOMAIN}\""; \
	  echo "  centralClusterName: \"$${CENTRAL_CLUSTER_NAME}\""; \
	  echo "  servicesClusterName: \"$${SERVICES_CLUSTER_NAME}\""; \
	  echo "  appsSubdomain: \"$${APPS_SUBDOMAIN}\""; \
	  echo "  centralAppsDomain: \"$${CENTRAL_APPS_DOMAIN}\""; \
	  echo "  servicesAppsDomain: \"$${SERVICES_APPS_DOMAIN}\""; \
	  echo "  dnsForwarderZone: \"$${DNS_FORWARDER_ZONE}\""; \
	  echo '  dnsForwarderIps:'; \
	  echo "$$ips_yaml"; \
	  echo 'servicesCluster:'; \
	  echo "  server: \"$${OCP_SERVICES_SERVER}\""; \
	  echo 'oci:'; \
	  echo "  registry: \"$${OCI_HOST}\""; \
	  echo "  repositoryBase: \"$${OCI_REPOSITORY_BASE}\""; \
	} > "$$outdir/values-lab.yaml"
	@$(call ok_print,Wrote $$outdir/values-lab.yaml)

.PHONY: upload-lab-config
upload-lab-config: check-env-central ## Upload lab topology from .env to Vault (central/data/lab-config) + ConfigMap
	@test -f "$(LAB_ENV_FILE)" || { echo "Missing $(LAB_ENV_FILE) — copy .env.example to .env and fill values"; exit 1; }
	@set -a; . "$(LAB_ENV_FILE)"; set +a; \
	$(call sovereign_login_central); \
	VAULT_ADDR="$${VAULT_CENTRAL_URL:-$$VAULT_ADDR}"; \
	if [ -z "$$VAULT_ADDR" ]; then echo "VAULT_CENTRAL_URL or VAULT_ADDR required"; exit 1; fi; \
	if [ -z "$$VAULT_TOKEN" ]; then \
	  VAULT_TOKEN=$$(oc get secret vault-init-secrets -n central-vault -o jsonpath='{.data.root_token}' 2>/dev/null | base64 -d); \
	fi; \
	if [ -z "$$VAULT_TOKEN" ]; then echo "VAULT_TOKEN not set and vault-init-secrets not readable"; exit 1; fi; \
	payload='{"data":{'; \
	first=1; \
	for key in $(LAB_CONFIG_KEYS); do \
	  val=$$(eval echo \$$$$key); \
	  [ -z "$$val" ] && continue; \
	  json_key=$$(echo "$$key" | tr '[:upper:]' '[:lower:]'); \
	  esc=$$(printf '%s' "$$val" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))'); \
	  if [ $$first -eq 1 ]; then first=0; else payload="$$payload,"; fi; \
	  payload="$$payload\"$$json_key\":$$esc"; \
	done; \
	payload="$$payload}}"; \
	code=$$(curl -sk -o /tmp/lab-config-vault.json -w '%{http_code}' \
	  -H "X-Vault-Token: $$VAULT_TOKEN" \
	  -H 'Content-Type: application/json' \
	  -X POST "$$VAULT_ADDR/v1/$(LAB_VAULT_PATH)" \
	  -d "$$payload"); \
	if [ "$$code" != "200" ] && [ "$$code" != "204" ]; then \
	  echo "Vault route write failed (HTTP $$code); trying in-cluster via scripts/unseal-and-upload-lab-config.py"; \
	  python3 "$(CURDIR)/../scripts/unseal-and-upload-lab-config.py" || { \
	    echo "Vault write failed (HTTP $$code):"; cat /tmp/lab-config-vault.json; exit 1; \
	  }; \
	else \
	  $(call ok_print,Uploaded lab-config to Vault $(LAB_VAULT_PATH)); \
	fi; \
	cm_args=; \
	for key in $(LAB_CONFIG_KEYS); do \
	  val=$$(eval echo \$$$$key); \
	  [ -z "$$val" ] && continue; \
	  cm_key=$$(echo "$$key" | tr '[:upper:]' '[:lower:]'); \
	  cm_args="$$cm_args --from-literal=$$cm_key=$$val"; \
	done; \
	oc create configmap $(LAB_CONFIGMAP_NAME) -n $(LAB_CONFIGMAP_NS) $$cm_args \
	  --dry-run=client -o yaml | oc apply -f - >/dev/null; \
	$(call ok_print,Applied ConfigMap $(LAB_CONFIGMAP_NS)/$(LAB_CONFIGMAP_NAME))

.PHONY: fetch-lab-config
fetch-lab-config: check-env-central ## Fetch lab-config from Vault and write local .env.lab (gitignored)
	@set -a; [ -f "$(LAB_ENV_FILE)" ] && . "$(LAB_ENV_FILE)"; set +a; \
	$(call sovereign_login_central); \
	VAULT_ADDR="$${VAULT_CENTRAL_URL:-$$VAULT_ADDR}"; \
	if [ -z "$$VAULT_TOKEN" ]; then \
	  VAULT_TOKEN=$$(oc get secret vault-init-secrets -n central-vault -o jsonpath='{.data.root_token}' 2>/dev/null | base64 -d); \
	fi; \
	curl -sk -H "X-Vault-Token: $$VAULT_TOKEN" \
	  "$$VAULT_ADDR/v1/$(LAB_VAULT_PATH)" \
	  | python3 -c 'import json,sys; d=json.load(sys.stdin).get("data",{}).get("data",{}); print("\n".join(f"{k.upper()}={v}" for k,v in sorted(d.items())))' \
	  > "$(abspath $(LAB_ENV_FILE)).lab"; \
	@$(call ok_print,Wrote $(LAB_ENV_FILE).lab)

.PHONY: sync-lab-helm-params
sync-lab-helm-params: check-env-central ## Patch ApplicationSet / sovereign-central-apps with lab helm.parameters from .env
	@test -f "$(LAB_ENV_FILE)" || { echo "Missing $(LAB_ENV_FILE)"; exit 1; }
	@set -a; . "$(LAB_ENV_FILE)"; set +a; \
	$(call sovereign_login_central); \
	python3 "$(CURDIR)/scripts/sync-lab-helm-params.py"
	@$(call ok_print,Synced lab helm.parameters to ApplicationSet/Application)
