---
- name: Mark CloudOSO as failed
  operator_sdk.util.k8s_status:
    api_version: hybridsovereign.redhat/v1alpha1
    kind: CloudOSO
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      status: "failed"
      lastReconciledAt: "{{ lookup('pipe', 'date -u +%Y-%m-%dT%H:%M:%S.000000Z') }}"
      message: "{{ ansible_failed_result.msg | default(ansible_failed_task.name | default('Reconciliation failed')) }}"
  ignore_errors: true
