---
- name: Mark CloudOSO as reconciling
  operator_sdk.util.k8s_status:
    api_version: hybridsovereign.redhat/v1alpha1
    kind: CloudOSO
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      status: "reconciling"
      lastReconciledAt: "{{ lookup('pipe', 'date -u +%Y-%m-%dT%H:%M:%S.000000Z') }}"
