---
- name: RbacConfig Create Rulebook
  hosts: all
  sources:
    - ansible.eda.event_stream:
        event_stream_name: sovereign-operator-events
  rules:
    - name: Handle RbacConfig Create
      condition: event.payload.reason in ["RbacConfigCreateRequested", "RbacConfigReconcileRequested"] and event.payload.regarding.kind == "RbacConfig"
      action:
        run_playbook:
          name: rbacconfig-provision-playbook.yml
          extra_vars:
            event_payload: "{{ event.payload }}"
