quay_url: "{{ lookup('env', 'QUAY_URL') | default('https://svc-sovereign-registry-quay-quay-enterprise.apps.services.lab.example.com', true) }}"
quay_internal_url: "{{ lookup('env', 'QUAY_INTERNAL_URL') | default('http://svc-sovereign-registry-quay-app.quay-enterprise.svc:443', true) }}"
