namespace: sovereign-cloud
pluginsNamespace: sovereign-cloud-plugins
installCRDs: true

image:
  repository: /hybrid-sovereign/hybridsovereign-primary-operator
  tag: "0.1.0"
  pullPolicy: Always

imagePullSecrets:
  - name: quay-pull-secret

namespaceOperator:
  image:
    repository: /hybrid-sovereign/hybridsovereign-namespace-operator
    tag: "0.1.0"
  chartVersion: "0.1.0"

serviceAccount:
  name: hybridsovereign-primary-operator

resources:
  limits:
    cpu: 500m
    memory: 1536Mi
  requests:
    cpu: 10m
    memory: 512Mi

replicas: 2

amqKafka:
  enabled: true
  vaultPath: amq-producer
  secretStoreName: vault-backend
  secretStoreKind: ClusterSecretStore

metrics:
  enabled: true
