apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hybridsovereign-namespace-operator
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "namespace-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["hybridsovereign.redhat"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hybridsovereign-namespace-operator
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hybridsovereign-namespace-operator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
