{{- if .Values.amqKafka.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amq-producer-credentials
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.amqKafka.secretStoreName }}
    kind: {{ .Values.amqKafka.secretStoreKind }}
  target:
    name: amq-producer-credentials
    creationPolicy: Owner
  data:
    - secretKey: bootstrap_servers
      remoteRef:
        key: {{ .Values.amqKafka.vaultPath }}
        property: bootstrap_servers
    - secretKey: topic
      remoteRef:
        key: {{ .Values.amqKafka.vaultPath }}
        property: topic
    - secretKey: username
      remoteRef:
        key: {{ .Values.amqKafka.vaultPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.amqKafka.vaultPath }}
        property: password
    - secretKey: ca.crt
      remoteRef:
        key: {{ .Values.amqKafka.vaultPath }}
        property: ca_cert
    - secretKey: security_protocol
      remoteRef:
        key: {{ .Values.amqKafka.vaultPath }}
        property: security_protocol
    - secretKey: sasl_mechanism
      remoteRef:
        key: {{ .Values.amqKafka.vaultPath }}
        property: sasl_mechanism
{{- end }}
