apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "primary-operator.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
