{{- if .Values.gitea.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: iaac-gitea-token
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.gitea.externalSecret.secretStoreName }}
    kind: {{ .Values.gitea.externalSecret.secretStoreKind }}
  target:
    name: {{ .Values.gitea.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.gitea.externalSecret.tokenKey }}
      remoteRef:
        key: {{ .Values.gitea.externalSecret.vaultPath }}
        property: admin_token
{{- end }}
