- name: AAPConfig Create Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle AAPConfig Create
    condition: event.payload.reason | default(event.message.reason | default('')) in ["AAPConfigCreateRequested", "AAPConfigReconcileRequested"] and event.payload.regarding.kind | default(event.message.regarding.kind | default(''))
      == "AAPConfig"
    action:
      run_job_template:
        name: aapconfig-provision
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
