- name: AAPOrg Delete Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle AAPOrg Delete
    condition: event.payload.reason | default(event.message.reason | default('')) == "AAPOrgDeleteRequested" and event.payload.regarding.kind | default(event.message.regarding.kind | default(''))
      == "AAPOrg"
    action:
      run_job_template:
        name: aaporg-teardown
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
