- name: Assignment Create Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle Assignment Create
    condition: event.payload.reason in ["AssignmentCreateRequested", "AssignmentReconcileRequested"]
      and event.payload.regarding.kind == "Assignment"
    action:
      run_job_template:
        name: assignment-provision
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
