- name: Assignment Delete Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle Assignment Delete
    condition: event.payload.reason == "AssignmentDeleteRequested" and event.payload.regarding.kind
      == "Assignment"
    action:
      run_job_template:
        name: assignment-teardown
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
