- name: CloudAWS Create Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle CloudAWS Create
    condition: event.payload.reason | default(event.message.reason | default('')) in ["CloudAWSCreateRequested", "CloudAWSReconcileRequested"]
      and event.payload.regarding.kind | default(event.message.regarding.kind | default('')) == "CloudAWS"
    action:
      run_job_template:
        name: cloudaws-provision
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
