- name: CloudOSO Delete Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle CloudOSO Delete
    condition: event.payload.reason | default(event.message.reason | default('')) == "CloudOSODeleteRequested" and event.payload.regarding.kind | default(event.message.regarding.kind | default(''))
      == "CloudOSO"
    action:
      run_job_template:
        name: cloudoso-teardown
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
