---
- name: OpenStackMigration Create Rulebook
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: kafka.apps.central.example.com
        port: "443"
        topic: hybridsovereign-events
        group_id: eda-openstack-migration-create
        security_protocol: SASL_SSL
        sasl_mechanism: SCRAM-SHA-512
        sasl_plain_username: "{{ KAFKA_USERNAME }}"
        sasl_plain_password: "{{ KAFKA_PASSWORD }}"
        check_hostname: false
        verify_mode: CERT_NONE
  rules:
    - name: Handle OpenStackMigration Request
      condition: event.payload.reason in ["OpenStackMigrationCreateRequested", "OpenStackMigrationReconcileRequested"] and event.payload.regarding.kind == "OpenStackMigration"
      action:
        run_job_template:
          name: openstack-migration-dummy
          organization: sovereign
          job_args:
            extra_vars:
              event_payload: "{{ event.payload }}"
