- name: Persona Delete Automation
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle Persona Delete
    condition: event.payload.reason == "PersonaDeleteRequested" and event.payload.regarding.kind
      == "Persona"
    action:
      run_job_template:
        name: persona-teardown
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
