- name: PlatformOpenshift Create Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle PlatformOpenshift Create
    condition: event.payload.reason | default(event.message.reason | default('')) in ["PlatformOpenshiftCreateRequested", "PlatformOpenshiftReconcileRequested"]
      and event.payload.regarding.kind | default(event.message.regarding.kind | default('')) == "PlatformOpenshift"
    action:
      run_job_template:
        name: platformopenshift-provision
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
