- name: QuayOrg Delete Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle QuayOrg Delete
    condition: event.payload.reason == "QuayOrgDeleteRequested" and event.payload.regarding.kind
      == "QuayOrg"
    action:
      run_job_template:
        name: quayorg-teardown
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
