- name: QuayOrg Create Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle QuayOrg Create
    condition: event.payload.reason | default(event.message.reason | default('')) in ["QuayOrgCreateRequested", "QuayOrgReconcileRequested"] and event.payload.regarding.kind | default(event.message.regarding.kind | default(''))
      == "QuayOrg"
    action:
      run_job_template:
        name: quayorg-provision
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
