---
- name: QuayConfig Create Rulebook
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: kafka.apps.central.example.com
        port: "443"
        topic: hybridsovereign-events
        group_id: eda-quayconfig-create
        security_protocol: SASL_SSL
        sasl_mechanism: SCRAM-SHA-512
        sasl_plain_username: "{{ KAFKA_USERNAME }}"
        sasl_plain_password: "{{ KAFKA_PASSWORD }}"
        check_hostname: false
        verify_mode: CERT_NONE
  rules:
    - name: Handle QuayConfig Create
      condition: event.body.payload.reason in ["QuayConfigCreateRequested", "QuayConfigReconcileRequested"] and event.body.payload.regarding.kind == "QuayConfig"
      action:
        run_job_template:
          name: quayconfig-provision
          organization: sovereign
          job_args:
            extra_vars:
              event_payload: "{{ event.body.payload }}"
