- name: QuayConfig Create Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle QuayConfig Create
    condition: event.payload.reason | default(event.message.reason | default('')) in ["QuayConfigCreateRequested", "QuayConfigReconcileRequested"] and event.payload.regarding.kind | default(event.message.regarding.kind | default(''))
      == "QuayConfig"
    action:
      run_job_template:
        name: quayconfig-provision
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
