- name: RbacConfig Create Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle RbacConfig Create
    condition: event.payload.reason | default(event.message.reason | default('')) in ["RbacConfigCreateRequested", "RbacConfigReconcileRequested"] and event.payload.regarding.kind | default(event.message.regarding.kind | default(''))
      == "RbacConfig"
    action:
      run_job_template:
        name: rbacconfig-provision
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
