---
- name: RBACConfig Create Rulebook
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: "hybridsovereign-kafka-kafka-bootstrap-amq-streams.apps.shc-cental5.lab.signal9.gg"
        port: "443"
        topic: hybridsovereign-events
        group_id: eda-rbacconfig-create
        security_protocol: SASL_SSL
        sasl_mechanism: SCRAM-SHA-512
        sasl_plain_username: "{{ KAFKA_USERNAME }}"
        sasl_plain_password: "{{ KAFKA_PASSWORD }}"
        check_hostname: false
        verify_mode: CERT_NONE
  rules:
    - name: Handle RBACConfig Create
      condition: event.body.payload.reason in ["RbacConfigCreateRequested", "RbacConfigReconcileRequested", "RBACConfigCreateRequested", "RBACConfigReconcileRequested"] and event.body.payload.regarding.kind in ["RbacConfig", "RBACConfig"]
      action:
        run_job_template:
          name: rbacconfig-provision
          organization: sovereign
          job_args:
            extra_vars:
              event_payload: "{{ event.body.payload }}"
