- name: Team Create Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle Team Create
    condition: event.payload.reason in ["TeamCreateRequested", "TeamReconcileRequested"] and event.payload.regarding.kind
      == "Team"
    action:
      run_job_template:
        name: team-provision
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
