- name: Vault Delete Rulebook
  hosts: all
  sources:
  - ansible.eda.event_stream:
      event_stream_name: sovereign-operator-events
  rules:
  - name: Handle Vault Delete
    condition: event.payload.reason | default(event.message.reason | default('')) == "VaultDeleteRequested" and event.payload.regarding.kind | default(event.message.regarding.kind | default(''))
      == "Vault"
    action:
      run_job_template:
        name: vault-teardown
        organization: sovereign
        job_args:
          extra_vars:
            event_payload: '{{ event.payload }}'
