# Sample VaultKV mounted on acme-vault
apiVersion: hybridsovereign.redhat/v1alpha1
kind: VaultKV
metadata:
  name: acme-app-secrets
  namespace: entity-acme-corp
spec:
  vault: acme-vault
  vaultAdminRbac:
    - acme-vault-admins
  vaultReaderRbac:
    - acme-developers
    - acme-operators
