{{- if .Values.gitopsOperator.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
  labels:
    {{- include "ocp-base.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.gitopsOperator.channel | quote }}
  installPlanApproval: {{ .Values.gitopsOperator.installPlanApproval }}
  name: openshift-gitops-operator
  source: {{ .Values.gitopsOperator.source | quote }}
  sourceNamespace: {{ .Values.gitopsOperator.sourceNamespace | quote }}
{{- end }}
