---
plugin_rbac_operator_namespace: sovereign-cloud-plugins
plugin_rbac_keycloak_realm: sovereign-tenants
plugin_rbac_keycloak_url_default: "https://rhbk-services.apps.services.{{ lookup('env', 'LAB_DOMAIN') }}"
eda_dashboard_host: "https://sovereign-aap-aap.apps.central.{{ lookup('env', 'LAB_DOMAIN') }}"
