---
- name: PlatformOpenshift Create Rulebook
  hosts: all
  sources:
    - ansible.eda.event_stream:
        event_stream_name: sovereign-operator-events
  rules:
    - name: Handle PlatformOpenshift Create
      condition: event.payload.reason in ["PlatformOpenshiftCreateRequested", "PlatformOpenshiftReconcileRequested"] and event.payload.regarding.kind == "PlatformOpenshift"
      action:
        run_playbook:
          name: platformopenshift-provision-playbook.yml
          extra_vars:
            event_payload: "{{ event.payload }}"
