---
- name: QuayOrg Create Rulebook
  hosts: all
  sources:
    - ansible.eda.event_stream:
        event_stream_name: sovereign-operator-events
  rules:
    - name: Handle QuayOrg Create
      condition: event.payload.reason in ["QuayOrgCreateRequested", "QuayOrgReconcileRequested"] and event.payload.regarding.kind == "QuayOrg"
      action:
        run_playbook:
          name: quayorg-provision-playbook.yml
          extra_vars:
            event_payload: "{{ event.payload }}"
