---
- name: Entity Create Rulebook
  hosts: all
  sources:
    - ansible.eda.event_stream:
        event_stream_name: sovereign-operator-events
  rules:
    - name: Handle Entity Create
      condition: event.payload.reason in ["EntityCreateRequested", "EntityReconcileRequested"] and event.payload.regarding.kind == "Entity"
      action:
        run_playbook:
          name: entity-provision-playbook.yml
          extra_vars:
            event_payload: "{{ event.payload }}"
